//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoutryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoutryMaster()
        {
            this.CustomerMasters = new HashSet<CustomerMaster>();
        }
    
        public int countryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> CustomerVm_CustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerMaster> CustomerMasters { get; set; }
    }
}
