//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CountryId { get; set; }
        public int ProductId { get; set; }
    
        public virtual CoutryMaster CoutryMaster { get; set; }
    }
}
